stages:
  - test
  - integration-test
  - build

docker-build-master:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA" .
    - docker push "$CI_REGISTRY_IMAGE"
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA"
  only:
    - master

docker-build:
  # Official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA"
  except:
    - master


test:
  image: mcr.microsoft.com/dotnet/core/sdk:3.1
  stage: test
  script:
    - cd HCrawler.Test && dotnet test  --logger:junit /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura
  artifacts:
    reports:
      cobertura: HCrawler.Test/coverage.cobertura.xml
      junit:
        - HCrawler.Test/TestResults/TestResults.xml

integration-test:
  image: mcr.microsoft.com/dotnet/core/sdk:3.1
  stage: test
  script:
    - dotnet run --project HCrawler.DB
    - cd HCrawler.IntegrationTest && dotnet test  --logger:junit /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura
  artifacts:
    reports:
      cobertura: HCrawler.IntegrationTest/coverage.cobertura.xml
      junit:
        - HCrawler.IntegrationTest/TestResults/TestResults.xml
